version: 2
jobs:
  tests:
    machine: true
    steps:
      - checkout
      - run: docker -f Dockerfile-tests build . -t panopticon
      - run: docker -f Dockerfile-tests run -t --rm panopticon

workflows:
  version: 2
  build:
    jobs:
      - tests:
          filters:
            branches:
              only: /develop|master|neilj.*/
